### PR TITLE
implement changes found in issue #4 - Partially empty member...

### PR DESCRIPTION
**Pull request by hailthemelody**
Link to issue:
https://github.com/castlamp/zenbership/issues/4

### CODE REVIEW

**Comment by jbelelieu** [comment]
The $use_url variable is required as many users do not installation Zenbership at the base/root of their website. In those cases, all the links would be broken. Full URLs are required at setup.

**Comment by hailthemelody** [comment]
Ah I didn't check this condition. In my case I use it at the root of my website, and it's broken for me. Is there another alternative, like checking to see if it's at the root and not including $use_url?

**Comment by jbelelieu** [comment]
That is definitely something that is being worked on in v109. The installation is a key focus for that release.

**Comment by hailthemelody** [comment]
Understood. Thanks for your work!

**Pull request closed without merging**
